/**
 * @file MainWindow.hpp
 * @author Noak Palander noak.palander@protonmail.com
 * @version 1.0
 * 
 * @section LICENSE
 * 
 * Copyright 2020 Noak Palander
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), 
 *  to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 *  and/or sell copies of the Software, 
 *  and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 *  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, 
 *  TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * @section DESCRIPTION
 * 
 * The MainWindow file declares the MainWindow class and sets up it's children. It's visual config is auto generated
 *  and defined in ui_MainWindow.h and MainWindow.ui. The implementation of MainWindow.hpp is in MainWindow.cpp
 * 
 * @see ui_MainWindow.h
 * @see MainWindow.ui
 * @see MainWindow.cpp
 */

#pragma once                    // Include guard

#include <QMainWindow>          // QMainWindow
#include <memory>               // std::unique_ptr

// Forward declares Ui::MainWindow which is auto generated by Qt
namespace Ui { 
    class MainWindow;
}

/**
 * @class MainWindow
 * @brief Implements a mainwindow that sets up the child widgets, also the "starting point" of the program
 * @extends QMainWindow
 * 
 * MainWindow is also the starting point of the program and is defined in MainWindow.cpp
 * 
 * @see ui_MainWindow.h
 * @see MainWindow.ui
 * @see MainWindow.cpp
 */
class MainWindow : public QMainWindow {
public:
    /**
     * Constructor that constructs the result-widget and sets it's children
     * 
     * @param parent The parent object of the class, default initialized to nullptr
     */
    explicit MainWindow(QWidget* parent = nullptr);

    /**
     * Destructor that destroys the window
     */
    ~MainWindow();

private:
    Q_OBJECT
    std::unique_ptr<Ui::MainWindow> m_UI;   /**< Holds the mainwindow object in a smart pointer */ 
};